version: "3.9"
services:
  db:
    image: postgres:15
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-mafia}"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
      - ./db/seed.sql:/docker-entrypoint-initdb.d/002-seed.sql:ro

  cache:
    image: redis:7
    ports:
      - "${REDIS_PORT:-6379}:6379"

  api:
    build: ./api
    env_file:
      - ./.env.api
    ports:
      - "4000:4000"
    depends_on:
      - db
      - cache

  web:
    build: ./web
    environment:
      NEXT_PUBLIC_API_URL: "${NEXT_PUBLIC_API_URL:-http://localhost:4000}"
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
