app = "mafia-api-demo"
primary_region = "ams"

[build]
  dockerfile = "api/Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 1
